FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "AssistantService/AssistantService.csproj"
RUN dotnet publish "AssistantService/AssistantService.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore
    
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5215

ENTRYPOINT ["dotnet", "AssistantService.dll"]
