services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: aiassistant-postgres
    environment:
      POSTGRES_DB: AiAssistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  rabbitmq:
    image: rabbitmq:4-management
    container_name: aiassistant-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres_data: