@WebApplication1_HostAddress = http://localhost:5010

GET {{WebApplication1_HostAddress}}/api/articles
Accept: application/json

###

POST {{WebApplication1_HostAddress}}/api/articles
Content-Type: application/json

{
  "title": "Как сбросить пароль?",
  "content": "Для сброса пароля перейдите..."
}

###

GET {{WebApplication1_HostAddress}}/api/articles/{id}
Accept: application/json